---
- name: Update
  hosts: "{{group_name}}"
  tasks:
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:
      
    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt
      register: update_info

    - name: print updates
      debug: 
        msg: "{{update_info}}"

    - name: Install all security updates with automatic reboots
      ansible.windows.win_updates:
        category_names:
         - Microsoft Defender Antivirus
  #      - SecurityUpdates
        reboot: true
        reboot_timeout: 1800

    - name: Example from an Ansible Playbook
      ansible.builtin.ping:
