- name: Run Updates on Terminal Servers then wait 7 mins
  hosts: "{{group_name}}"
  tasks:
    ansible.windows.win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
      accept_list:
        - KB4093120
    state: installed
    reboot: yes
    reboot_timeout: 420
